### ISSUE TITLE
Invalid prop: type check failed for prop "label". Expected String with value "undefined", got Undefined

### ISSUE THREAD

**Issue by zadigus** [shopozor/common-frontend#18]
The following warning pops up in all the tests we run:
```
[Vue warn]: Invalid prop: type check failed for prop "label". Expected String with value "undefined", got Undefined 

found in

---> <PageLink> at common/src/components/SideDrawerContent/PageLink.vue
       <QList>
         <SideDrawerContent> at common/src/components/SideDrawerContent/SideDrawerContent.vue
           <QDrawer>
             <QLayout>
               <Layout> at common/src/layouts/parametricLayout.vue
                 <Layout> at src/layouts/layout.vue
                   <App> at src/App.vue
                     <Root>
```
Apparently, the error comes for the component located in 
```
common/src/components/SideDrawerContent/PageLink.vue
```
Apparently, an `Undefined` value is received where the string `"undefined"` is expected. To reproduce the problem and be able to debug that, you need to run the `management-frontend`'s cypress integration tests `login.spec.js`. In the chrome browser's window where the tests are run, you can enable the developer's tools and therefore debug what the problem is.

**Comment by zadigus** [comment]
I tried several things but I don't know what the real purpose of that label is and where it is coming from. One way to make the error disappear is this:
```
label: {
  type: String,
  default: undefined
}
```
in the script section. It's the opposite of what was previously put:
```
label: {
  type: String,
  required: true
}
```
Apparently, the value of the label is never set, therefore triggering the error.

**Comment by comteharbour** [comment]
The issue is solved. The cause was a misuse of the obsolete type `types.links.FAKE_SHOP` in the `src/router/links.js` file.
